apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microshop-dev
resources:
- ../base
- namespace.yaml
- ingress.yaml
- external-secret.yaml
patches:
- path: patches/replicas.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: api-gateway
- path: patches/serviceaccount.yaml
  target:
    version: v1
    kind: ServiceAccount
    name: microshop
images:
- name: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/frontend
  newName: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/frontend
  newTag: "b49abff149809cc83b13e7b7089125ff7624cc73"
- name: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/api-gateway
  newName: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/api-gateway
  newTag: "b49abff149809cc83b13e7b7089125ff7624cc73"
- name: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/user-service
  newName: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/user-service
  newTag: "b49abff149809cc83b13e7b7089125ff7624cc73"
- name: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/product-service
  newName: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/product-service
  newTag: "b49abff149809cc83b13e7b7089125ff7624cc73"
- name: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/order-service
  newName: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/order-service
  newTag: "b49abff149809cc83b13e7b7089125ff7624cc73"
- name: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/payment-service
  newName: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/payment-service
  newTag: "b49abff149809cc83b13e7b7089125ff7624cc73"
- name: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/notification-service
  newName: 185188589391.dkr.ecr.ap-south-1.amazonaws.com/microshop/notification-service
  newTag: "b49abff149809cc83b13e7b7089125ff7624cc73"