services:
  frontend:
    build: ./apps/frontend
    ports: ["3000:80"]
    depends_on: [api-gateway]
  api-gateway:
    build: ./apps/api-gateway
    environment:
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: http://localhost:3000
      USER_SERVICE_URL: http://user-service:4001
      PRODUCT_SERVICE_URL: http://product-service:4002
      ORDER_SERVICE_URL: http://order-service:4003
      PAYMENT_SERVICE_URL: http://payment-service:4004
    depends_on: [user-service,product-service,order-service,payment-service]
  user-service:
    build: ./apps/user-service
    environment: {PORT: 4001,JWT_SECRET: ${JWT_SECRET},DATABASE_URL: ${DATABASE_URL}}
  product-service:
    build: ./apps/product-service
    environment: {PORT: 4002,REDIS_URL: redis://redis:6379,DATABASE_URL: ${DATABASE_URL},JWT_SECRET: ${JWT_SECRET}}
    depends_on: [postgres,redis]
  order-service:
    build: ./apps/order-service
    environment: {PORT: 4003,RABBITMQ_URL: ${RABBITMQ_URL},DATABASE_URL: ${DATABASE_URL},JWT_SECRET: ${JWT_SECRET}}
    depends_on: [postgres,rabbitmq]
  payment-service:
    build: ./apps/payment-service
    environment: {PORT: 4004,RABBITMQ_URL: ${RABBITMQ_URL},DATABASE_URL: ${DATABASE_URL},JWT_SECRET: ${JWT_SECRET}}
    depends_on: [postgres,rabbitmq]
  notification-service:
    build: ./apps/notification-service
    environment: {PORT: 4005,RABBITMQ_URL: ${RABBITMQ_URL}}
    depends_on: [rabbitmq]
  postgres:
    image: postgres:16-alpine
    environment: {POSTGRES_DB: ${POSTGRES_DB},POSTGRES_USER: ${POSTGRES_USER},POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}}
    volumes: [pgdata:/var/lib/postgresql/data,./database/init:/docker-entrypoint-initdb.d:ro]
  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    volumes: [redisdata:/data]
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    environment: {RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER},RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}}
    ports: ["15672:15672"]
volumes: {pgdata: {},redisdata: {}}
