releaseTag: "b49abff149809cc83b13e7b7089125ff7624cc73"
global:
  registry: "185188589391.dkr.ecr.ap-south-1.amazonaws.com"
  imagePullPolicy: IfNotPresent
secretName: microshop/dev
networkPolicy:
  dependencyCidrs: ["10.20.0.0/16"]
ingress:
  host: dev.microshop.example.com
  certificateArn: ""
  enabled: false
hpa: { enabled: false, min: 1, max: 3, cpu: 70 }
services:
  frontend: { image: microshop/frontend, port: 80, replicas: 1, healthPath: / }
  api-gateway: { image: microshop/api-gateway, port: 4000, replicas: 2, healthPath: /health }
  user-service: { image: microshop/user-service, port: 4001, replicas: 1, healthPath: /health }
  product-service: { image: microshop/product-service, port: 4002, replicas: 1, healthPath: /health }
  order-service: { image: microshop/order-service, port: 4003, replicas: 1, healthPath: /health }
  payment-service: { image: microshop/payment-service, port: 4004, replicas: 1, healthPath: /health }
  notification-service: { image: microshop/notification-service, port: 4005, replicas: 1, healthPath: /health }
