apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microshop-prod
  namespace: argocd
spec:
  project: microshop
  source:
    repoURL: https://github.com/chauhan050790/microshop-v4-k8s-complete.git
    targetRevision: main
    path: helm/microshop
    helm:
      valueFiles: [values-prod.yaml]
      parameters:
      - name: releaseTag
        value: "0000000000000000000000000000000000000000"
      - name: global.registry
        value: "000000000000.dkr.ecr.ap-south-1.amazonaws.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: microshop-prod
  syncPolicy:
    syncOptions: [CreateNamespace=true]
