apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microshop-dev
  namespace: argocd
spec:
  project: microshop
  source:
    repoURL: https://github.com/chauhan050790/microshop-v4-k8s-complete.git
    targetRevision: main
    path: helm/microshop
    helm:
      valueFiles: [values-dev.yaml]
      parameters:
      - name: releaseTag
        value: "b49abff149809cc83b13e7b7089125ff7624cc73"
      - name: global.registry
        value: "185188589391.dkr.ecr.ap-south-1.amazonaws.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: microshop-dev
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
