apiVersion: v1
kind: ConfigMap
metadata:
  name: microshop-config
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: production
  CORS_ORIGIN: https://{{ .Values.ingress.host }}
  USER_SERVICE_URL: http://user-service:4001
  PRODUCT_SERVICE_URL: http://product-service:4002
  ORDER_SERVICE_URL: http://order-service:4003
  PAYMENT_SERVICE_URL: http://payment-service:4004
  NOTIFICATION_SERVICE_URL: http://notification-service:4005
