apiVersion: v1
kind: ServiceAccount
metadata:
  name: microshop
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.global.irsaRoleArn }}
    eks.amazonaws.com/role-arn: {{ . | quote }}
    {{- end }}
