name: Production Release
on:
  workflow_dispatch:
    inputs: {image_tag: {description: Immutable Git SHA,required: true}}
permissions: {contents: write,id-token: write}
jobs:
  release:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update production GitOps tag
      run: |
        sed -i "s/REPLACE_PROD_TAG/${{inputs.image_tag}}/g" argocd/application-prod.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add argocd/application-prod.yaml
        git commit -m "release: ${{inputs.image_tag}}" || true
        git push

